#!/usr/bin/env python3
"""Experiment E7: exact on-chain verification cost from the EVM gas schedule.

Why this exists
---------------
The previously reported per-cluster gas figure was measured with
``enableMockVerifier()`` active (see ``scripts/deploy_global_audit.cjs``), so it
records contract bookkeeping only and excludes Groth16 verification entirely.
It therefore cannot support a claim about end-to-end on-chain audit cost, and
it cannot settle whether the global verification cost is O(sqrt(k)) or O(k).

This model computes the verification cost exactly from the published EVM gas
schedule.  Precompile costs on BN254 are input-independent constants, so the
result is exact rather than estimated, and any reader can re-derive it from the
EIPs cited below.

Gas schedule (all values are protocol constants, not measurements)
------------------------------------------------------------------
* EIP-196 / EIP-197, repriced by EIP-1108 (Istanbul):
    ecAdd  (0x06)      150 gas
    ecMul  (0x07)    6,000 gas
    ecPairing (0x08) 45,000 + 34,000 * (number of pairs)
* EIP-2028 (Istanbul): calldata 16 gas per non-zero byte, 4 per zero byte.
* EIP-2929 / EIP-3529 (Berlin/London): cold storage slot access 2,100 gas;
  SSTORE zero -> non-zero 20,000; SSTORE non-zero -> non-zero 2,900.
* Yellow Paper: transaction base 21,000; LOG topic 375; LOG data 8 gas/byte.

The two interfaces
------------------
``per-chain``  Algorithm 1 as previously written: the public-input vector is
               every member chain's new root plus cluster id and round, so a
               cluster with B_max slots has B_max + 2 public inputs.
``commitment`` The corrected interface: the public input is one constant-size
               cluster commitment plus cluster id and round, and the binding of
               every member root to that commitment is proved inside the
               aggregation circuit.  Three public inputs regardless of B_max.

Outputs
-------
result/revision2/e7_onchain_cost.csv
result/revision2/e7_summary.json
"""

from __future__ import annotations

import argparse
import json
import math
import os
from typing import Dict, List

OUT = os.path.join(os.path.dirname(__file__), "..", "..", "result", "revision2")

# --- EVM gas constants -----------------------------------------------------
G_TX_BASE = 21_000
G_CALLDATA_NONZERO = 16
G_CALLDATA_ZERO = 4
G_ECADD = 150
G_ECMUL = 6_000
G_PAIRING_BASE = 45_000
G_PAIRING_PER_PAIR = 34_000
G_SSTORE_SET = 20_000          # zero -> non-zero
G_SSTORE_RESET = 2_900         # non-zero -> non-zero
G_COLD_SLOAD = 2_100
G_LOG_TOPIC = 375
G_LOG_BYTE = 8

# Groth16 over BN254 as generated by snarkjs: the final check is a single
# ecPairing call with four pairs, e(A,B) e(alpha,beta)^-1 e(vk_x,gamma)^-1
# e(C,delta)^-1.
GROTH16_PAIRS = 4
GROTH16_MISC_EVM = 5_000       # negation, memory, control flow around the check

PROOF_BYTES = 8 * 32           # A(2) + B(4) + C(2) field elements
WORD = 32


def groth16_verify_gas(n_public: int) -> int:
    """Exact verification cost for n public inputs, excluding calldata."""
    accumulate = n_public * (G_ECMUL + G_ECADD)
    pairing = G_PAIRING_BASE + GROTH16_PAIRS * G_PAIRING_PER_PAIR
    return accumulate + pairing + GROTH16_MISC_EVM


def calldata_gas(n_bytes: int, zero_fraction: float = 0.06) -> int:
    """Calldata cost.  Field elements are dense, so most bytes are non-zero."""
    zero = int(round(n_bytes * zero_fraction))
    return zero * G_CALLDATA_ZERO + (n_bytes - zero) * G_CALLDATA_NONZERO


def storage_gas(n_words_updated: int, n_words_new: int = 0) -> int:
    return (n_words_updated * (G_SSTORE_RESET + G_COLD_SLOAD)
            + n_words_new * (G_SSTORE_SET + G_COLD_SLOAD))


def event_gas(n_topics: int, data_bytes: int) -> int:
    return G_LOG_TOPIC * (n_topics + 1) + G_LOG_BYTE * data_bytes


# --- per-transaction models ------------------------------------------------


def flat_chain_tx(n_public: int = 3) -> Dict[str, int]:
    """One ordinary chain submits and verifies its own audit proof.

    Public inputs: old root, new root, chain id.  Storage: the chain's root is
    updated in place; one event is emitted.
    """
    cd = calldata_gas(PROOF_BYTES + n_public * WORD + 4)
    return {
        "tx_base": G_TX_BASE,
        "calldata": cd,
        "verify": groth16_verify_gas(n_public),
        "storage": storage_gas(n_words_updated=2),
        "event": event_gas(2, 64),
    }


def hzka_cluster_tx(b_max: int, interface: str) -> Dict[str, int]:
    """One cluster head submits and the auditors verify one aggregate proof."""
    if interface == "commitment":
        n_public = 3                      # cluster commitment, cluster id, round
        payload_words = n_public
    elif interface == "per-chain":
        n_public = b_max + 2              # every member root, cluster id, round
        payload_words = n_public
    else:
        raise ValueError(interface)
    cd = calldata_gas(PROOF_BYTES + payload_words * WORD + 4)
    return {
        "tx_base": G_TX_BASE,
        "calldata": cd,
        "verify": groth16_verify_gas(n_public),
        "storage": storage_gas(n_words_updated=2),
        "event": event_gas(2, 64),
    }


def total(d: Dict[str, int]) -> int:
    return sum(d.values())


# --- round-level accounting ------------------------------------------------


def round_cost(k: int, b_max: int) -> Dict[str, float]:
    m = math.ceil(math.sqrt(k))
    flat = flat_chain_tx()
    hz_commit = hzka_cluster_tx(b_max, "commitment")
    hz_perchain = hzka_cluster_tx(b_max, "per-chain")

    flat_round = k * total(flat)
    commit_round = m * total(hz_commit)
    perchain_round = m * total(hz_perchain)

    # Asymptotic decomposition: which part of the cost scales with k?
    flat_pairing = k * (G_PAIRING_BASE + GROTH16_PAIRS * G_PAIRING_PER_PAIR)
    commit_pairing = m * (G_PAIRING_BASE + GROTH16_PAIRS * G_PAIRING_PER_PAIR)
    perchain_pairing = commit_pairing
    flat_scalar = k * 3 * (G_ECMUL + G_ECADD)
    commit_scalar = m * 3 * (G_ECMUL + G_ECADD)
    perchain_scalar = m * (b_max + 2) * (G_ECMUL + G_ECADD)

    return {
        "k": k,
        "clusters": m,
        "b_max": b_max,
        "flat_per_tx": total(flat),
        "hzka_commitment_per_tx": total(hz_commit),
        "hzka_perchain_per_tx": total(hz_perchain),
        "flat_round": flat_round,
        "hzka_commitment_round": commit_round,
        "hzka_perchain_round": perchain_round,
        "reduction_commitment": flat_round / commit_round,
        "reduction_perchain": flat_round / perchain_round,
        "flat_pairing_gas": flat_pairing,
        "hzka_pairing_gas": commit_pairing,
        "flat_scalar_gas": flat_scalar,
        "hzka_commitment_scalar_gas": commit_scalar,
        "hzka_perchain_scalar_gas": perchain_scalar,
        "perchain_scalar_share": perchain_scalar / perchain_round,
    }


def breakdown_table(b_max: int) -> List[Dict[str, object]]:
    rows = []
    for label, d in (("Flat, per chain", flat_chain_tx()),
                     ("H-ZKA, commitment", hzka_cluster_tx(b_max, "commitment")),
                     ("H-ZKA, per-chain inputs", hzka_cluster_tx(b_max, "per-chain"))):
        row = {"interface": label}
        row.update(d)
        row["total"] = total(d)
        rows.append(row)
    return rows


def write_csv(path: str, rows: List[Dict]) -> None:
    if not rows:
        return
    cols = list(rows[0].keys())
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(",".join(cols) + "\n")
        for r in rows:
            fh.write(",".join(
                f"{r[c]:.6f}" if isinstance(r[c], float) else str(r[c])
                for c in cols) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--b-max", type=int, default=15)
    args = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)

    rows = [round_cost(k, args.b_max) for k in (25, 50, 100, 150, 200)]
    write_csv(os.path.join(OUT, "e7_onchain_cost.csv"), rows)

    bd = breakdown_table(args.b_max)
    write_csv(os.path.join(OUT, "e7_tx_breakdown.csv"), bd)

    with open(os.path.join(OUT, "e7_summary.json"), "w", encoding="utf-8") as fh:
        json.dump({
            "config": vars(args),
            "gas_schedule": {
                "source": "EIP-196/197 repriced by EIP-1108; EIP-2028; "
                          "EIP-2929/3529; Ethereum Yellow Paper",
                "ecAdd": G_ECADD, "ecMul": G_ECMUL,
                "pairing_base": G_PAIRING_BASE,
                "pairing_per_pair": G_PAIRING_PER_PAIR,
                "calldata_nonzero": G_CALLDATA_NONZERO,
                "calldata_zero": G_CALLDATA_ZERO,
                "tx_base": G_TX_BASE,
                "groth16_pairs": GROTH16_PAIRS,
            },
            "per_tx_breakdown": bd,
            "rounds": rows,
        }, fh, indent=2)

    print("E7 complete.  Exact on-chain verification cost from the EVM gas schedule.\n")
    print("Per-transaction breakdown (B_max = %d):" % args.b_max)
    for r in bd:
        print("  %-24s base %6d  calldata %6d  verify %7d  storage %6d  event %5d  = %7d"
              % (r["interface"], r["tx_base"], r["calldata"], r["verify"],
                 r["storage"], r["event"], r["total"]))
    print("\nPer-round totals:")
    print("  %4s %3s %12s %14s %14s %8s %8s" %
          ("k", "M", "flat", "commitment", "per-chain", "red_c", "red_pc"))
    for r in rows:
        print("  %4d %3d %12d %14d %14d %7.2fx %7.2fx" %
              (r["k"], r["clusters"], r["flat_round"],
               r["hzka_commitment_round"], r["hzka_perchain_round"],
               r["reduction_commitment"], r["reduction_perchain"]))
    print("\nScaling: under the per-chain interface the scalar-multiplication term is")
    print("O(M*B_max) = O(k); at k=200 it is %.1f%% of the H-ZKA round cost."
          % (100 * rows[-1]["perchain_scalar_share"]))


if __name__ == "__main__":
    main()
