// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Denomination$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Denomination";
  readonly sourceName: "contracts/libraries/Denomination.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220c0e0db9c925942ed43ac3c538328f7db1587d1b39e4d6d85675404f3046cdad064736f6c63430008180033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220c0e0db9c925942ed43ac3c538328f7db1587d1b39e4d6d85675404f3046cdad064736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/Denomination.sol";
  readonly buildInfoId: "solc-0_8_24-ba828cc3e29caeee2779b63b0600a648c5ede39f";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Denomination"]: Denomination$Type;
    ["contracts/libraries/Denomination.sol:Denomination"]: Denomination$Type;
  }
}