// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Groth16Verifier$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Groth16Verifier";
  readonly sourceName: "contracts/libraries/Groth16Verifier.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122076b293e8864ac1b1004c345474cad3c77f57518fc89b004cbdb7a5e9420b065064736f6c63430008180033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122076b293e8864ac1b1004c345474cad3c77f57518fc89b004cbdb7a5e9420b065064736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/Groth16Verifier.sol";
  readonly buildInfoId: "solc-0_8_24-ba828cc3e29caeee2779b63b0600a648c5ede39f";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Groth16Verifier"]: Groth16Verifier$Type;
    ["contracts/libraries/Groth16Verifier.sol:Groth16Verifier"]: Groth16Verifier$Type;
  }
}